module.exports = {
  example: [
    {
     pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 1',
      averageRating: 4.6,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 2',
      averageRating: 3.4,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 3',
      averageRating: 2.7,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 4',
      averageRating: 1.3,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 5',
      averageRating: 0.6,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 6',
      averageRating: 4.8,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
      name: 'Mofuu Mofuu Tippy Plushie 7',
      averageRating: 4.2,
      reviews: 12345,
      price: 100.00,
    },
    {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 8',
       averageRating: 2.6,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 9',
       averageRating: 2.1,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 10',
       averageRating: 1.1,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 11',
       averageRating: 4.2,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 12',
       averageRating: 2.6,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 13',
       averageRating: 4.8,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 14',
       averageRating: 1.2,
       reviews: 12345,
       price: 100.00,
     },
     {
      pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 15',
       averageRating: 3.6,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 16',
       averageRating: 4.4,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 17',
       averageRating: 4.7,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 18',
       averageRating: 3.3,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 19',
       averageRating: 2.6,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 20',
       averageRating: 1.8,
       reviews: 12345,
       price: 100.00,
     },
     {
       pictureURL: "https://ae01.alicdn.com/kf/HTB1I619lsuYBuNkSmRyq6AA3pXar/candice-guo-Super-cute-plush-toy-lovely-Tippy-rabbit-is-the-order-a-rabbit-soft-stuffed.jpg_220x220.jpg",
       name: 'Mofuu Mofuu Tippy Plushie 21',
       averageRating: 2.2,
       reviews: 12345,
       price: 100.00,
     },
  ],
};